### PR TITLE
Fix for the Task.Yield() and allow ConfigureAwait(true).

### LINKED ISSUE #9: Fix for the Task.Yield()
**ConfigureAwaitChecker** thinks `await Task.Yield();` instruction is obligated to be Configure-Awaited:

Yet it is not, since the `Task.Yield`'s result is not a `Task` and hence doesn't even have the method. Nor does it need the context switch option.

Please, fix the non-task `ConfigureAwait` rule.

### PR DESCRIPTION
**Pull request by MaxShoshin**
Close #9

### CODE REVIEW

**Comment by cincuranet** [comment]
Thanks for the PR. Unfortunately I don't agree with it, but I'm open to discussion.

* Checking only for `Task` and `Task<>` does not work with custom types, notably `ValueTask` and `ValueTask<>`.
* I don't think the `ConfigureAwait(true)` should be in code whatsoever. The `true` is default, so why write it? I personally skip the `private` for i.e. methods etc. ;)

**Comment by MaxShoshin** [comment]
Thanks for review!

* I agree about `ValueTask` and `ValueTask<>`, i'll think about it.

* About `ConfigureAwait(true)` yes, it is default behavior. But if you specify it that means that you thinking about necessary behavior and you need such one (`ConfigureAwait(true)` is applicable in Winforms applications for example). If you don't specify `ConfigureAwait(true)` it is not mean that you need such behavior: may be you just forget to add it. 

So I prefer to awoid `await` without specify `ConfigureAwait(true/false)` if it is applicable (as i use `await` for non tasks, like `Task.Yeld()`).

**Comment by MaxShoshin** [comment]
About `ValueTask` and `ValueTask<>`: i'm checking existance of `ConfigureAwait` member on expression type. If such member exists it should be specified.

**Comment by AgentFire** [comment]
The whole point of this package is to **force** the ConfigureAwait(false), which is the case for DLL-typed projects, so that this package would find those missing configure-awaits. In case of desktop application, the whole point of 100% configure-await-false is lost, so the analyzer rule shoudn't even be there.

So the ConfigureAwait(true) is, in fact, a mistake, given the context. I'm with @cincuranet here.

P.S.
The message "Possibly missing `ConfigureAwait(false)` call" can/should be changes to just "Missing <...>".

**Comment by MaxShoshin** [comment]
Many thanks for comments!

What we should do in desktop applications? Create additional rule package and use both in one solution? 

For desktop apps in most cases we need `ConfigureAwait(false)` to awoid unnecessary context switch. But on the top of code (UI handlers, etc.) we can use `ConfigureAwait(true)`.

Let us imagine that you review following code (without ConfigureAwait):
```C#
....
await DoSomethingAsync();
....
```
You can not correct determine situation:
* I really need to switch sync context back
* or I needn't capture context and just forget specify `ConfigureAwait(false)` 

So missing of the `ConfigureAwait(true/false)` I treat as warning. But in some cases I need to specify `ConfigureAwait(true)`.

My point is: developers are smart, if they use such analyzer they understand what they are doing. They need only little assistance to do not forget specify `ConfigureAwait`. If they get such warning they can decide what they can use as a parameter: `true` or `false`.

**Comment by cincuranet** [comment]
Easiest solution is to keep the real logic and UI code separate. The logic will live in its own assembly where the analyzer will be active and the UI code will not have it. For the small parts where one is not directly calling to the library and it's not UI related (hence the `ConfigureAwait(false)` could be there) the overhead isn't going to be a concern, because it's not going to be in hot path (else it should be in the library).

I don't think there's a one "correct" solution to this. And the usage is highly opinionated (similar to what this package should and shoudn't catch).

My $0.02.

**Comment by MaxShoshin** [comment]
I agree with you about separating UI from logic.

But sometimes separating by the placing code in different assemblies is overkill: you need to create 2 additional not really necessary assemblies (sometimes when you have only one UI implementation).

My proposal: may be create additional analyzer package which will support ConfigureAwait(true/false) and leave current analyzer to support only ConfigureAwait(true).

What do you think about it?

**Comment by cincuranet** [comment]
You can have multiple analyzers in one package, thus no need to create
another one. The other analyzer can be off by default and if somebody
needs it, (s)he can turn it on.
I'll think about it and also maybe somebody else can jump into this
conversation and share his/hers opinion.

**Comment by cincuranet** [comment]
I'll close this for now and if somebody has opinion about `ConfigureAwait(true)`, please comment and we can revisit it later.

**Pull request closed without merging**
